name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    with:
      jbang-trust-add: https://github.com/
    uses: jbanghub/.github/.github/workflows/shared-build.yml@main
